In [2]:
# %load ../../standard_import.txt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from mpl_toolkits.mplot3d import axes3d

pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_seq_items', None)
 
#%config InlineBackend.figure_formats = {'pdf',}
%matplotlib inline  

import seaborn as sns
sns.set_context('notebook')
sns.set_style('white')

In [3]:
# 创建大小为5的单位矩阵
def warmUpExercise():
    return(np.identity(5))

In [4]:
warmUpExercise()

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [8]:
data = np.loadtxt('linear_regression_data1.txt', delimiter=',')

In [10]:
# 读取矩阵第一维的长度
data.shape[0]

97L

In [11]:
# ones生成长度是97的一维度数组
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html
np.ones(data.shape[0])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
X = np.c_[np.ones(data.shape[0]),data[:,0]]
print(X)

[[  1.       6.1101]
 [  1.       5.5277]
 [  1.       8.5186]
 [  1.       7.0032]
 [  1.       5.8598]
 [  1.       8.3829]
 [  1.       7.4764]
 [  1.       8.5781]
 [  1.       6.4862]
 [  1.       5.0546]
 [  1.       5.7107]
 [  1.      14.164 ]
 [  1.       5.734 ]
 [  1.       8.4084]
 [  1.       5.6407]
 [  1.       5.3794]
 [  1.       6.3654]
 [  1.       5.1301]
 [  1.       6.4296]
 [  1.       7.0708]
 [  1.       6.1891]
 [  1.      20.27  ]
 [  1.       5.4901]
 [  1.       6.3261]
 [  1.       5.5649]
 [  1.      18.945 ]
 [  1.      12.828 ]
 [  1.      10.957 ]
 [  1.      13.176 ]
 [  1.      22.203 ]
 [  1.       5.2524]
 [  1.       6.5894]
 [  1.       9.2482]
 [  1.       5.8918]
 [  1.       8.2111]
 [  1.       7.9334]
 [  1.       8.0959]
 [  1.       5.6063]
 [  1.      12.836 ]
 [  1.       6.3534]
 [  1.       5.4069]
 [  1.       6.8825]
 [  1.      11.708 ]
 [  1.       5.7737]
 [  1.       7.8247]
 [  1.       7.0931]
 [  1.       5.0702]
 [  1.       

In [16]:
y = np.c_[data[:,1]]
print(y)

[[ 17.592  ]
 [  9.1302 ]
 [ 13.662  ]
 [ 11.854  ]
 [  6.8233 ]
 [ 11.886  ]
 [  4.3483 ]
 [ 12.     ]
 [  6.5987 ]
 [  3.8166 ]
 [  3.2522 ]
 [ 15.505  ]
 [  3.1551 ]
 [  7.2258 ]
 [  0.71618]
 [  3.5129 ]
 [  5.3048 ]
 [  0.56077]
 [  3.6518 ]
 [  5.3893 ]
 [  3.1386 ]
 [ 21.767  ]
 [  4.263  ]
 [  5.1875 ]
 [  3.0825 ]
 [ 22.638  ]
 [ 13.501  ]
 [  7.0467 ]
 [ 14.692  ]
 [ 24.147  ]
 [ -1.22   ]
 [  5.9966 ]
 [ 12.134  ]
 [  1.8495 ]
 [  6.5426 ]
 [  4.5623 ]
 [  4.1164 ]
 [  3.3928 ]
 [ 10.117  ]
 [  5.4974 ]
 [  0.55657]
 [  3.9115 ]
 [  5.3854 ]
 [  2.4406 ]
 [  6.7318 ]
 [  1.0463 ]
 [  5.1337 ]
 [  1.844  ]
 [  8.0043 ]
 [  1.0179 ]
 [  6.7504 ]
 [  1.8396 ]
 [  4.2885 ]
 [  4.9981 ]
 [  1.4233 ]
 [ -1.4211 ]
 [  2.4756 ]
 [  4.6042 ]
 [  3.9624 ]
 [  5.4141 ]
 [  5.1694 ]
 [ -0.74279]
 [ 17.929  ]
 [ 12.054  ]
 [ 17.054  ]
 [  4.8852 ]
 [  5.7442 ]
 [  7.7754 ]
 [  1.0173 ]
 [ 20.992  ]
 [  6.6799 ]
 [  4.0259 ]
 [  1.2784 ]
 [  3.3411 ]
 [ -2.6807 ]
 [  0.29678]
 [  3.8845 ]

In [ ]:

plt.scatter(X[:,1], y, s=30, c='r', marker='x', linewidths=1)